name: Build and deploy main

on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

jobs:
    build-container:
      runs-on: ubuntu-20.04

      steps:
          - name: Checking out
            uses: actions/checkout@v2

          - name: Building
            run: |
              mvn package
              mvn jacoco:report

          - name: Uploading coverage
            uses: codacy/codacy-coverage-reporter-action@v1
            with:
              api-token: ${{ secrets.CODACY_API_TOKEN }}
              coverage-reports: ./target/site/jacoco/jacoco.xml
            env:
              CODACY_PROJECT_NAME: "bodleian"
              CODACY_ORGANIZATION_PROVIDER: "gh"
              CODACY_USERNAME: "${{ github.repository_owner }}"

          - name: Containerizing
            run: ./scripts/containerize.sh
            env:
              IMAGE_NAME: "${{ github.repository }}:${{ github.sha }}"
              DOCKER_REGISTRY_USERNAME: "${{ secrets.DOCKER_REGISTRY_USERNAME }}"
              DOCKER_REGISTRY_TOKEN: "${{ secrets.DOCKER_REGISTRY_TOKEN }}"

    deploy:
      needs:
        - build-container
      runs-on: ubuntu-20.04

      steps:
        - name: Deploying...
          run: echo WIP...
