name: Pull request review

on:
  pull_request:
  workflow_dispatch:

jobs:
    pull-request-review:
      runs-on: ubuntu-20.04

      steps:
          - name: Checking out
            uses: actions/checkout@v2

